name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

# ✅ Give write permissions to allow pushing to output branch
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake from Custom Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          inputs: .github/snk/custom_grid.json
          outputs: |
            dist/dikshant-snake.svg
            dist/dikshant-snake-dark.svg?palette=github-dark
            dist/dikshant-snake.gif?color_snake=#39d353&color_dots=#0e4429,#006d32,#26a641,#39d353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation from custom grid [skip ci]"
